package com.example.musicapp.ui.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFE1C4FF)
val PurpleGrey80 = Color(0xFFDDD3E6)
val Pink80 = Color(0xFFF4C5D5)

val Purple40 = Color(0xFF7858A6)
val PurpleGrey40 = Color(0xFF6F6678)
val Pink40 = Color(0xFF8E5F70)

val md_theme_light_primary = Color(0xFF4E7B2C)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFBFEAB0)
val md_theme_light_onPrimaryContainer = Color(0xFF0D2700)
val md_theme_light_secondary = Color(0xFF687458)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDFECD2)
val md_theme_light_onSecondaryContainer = Color(0xFF1D260C)
val md_theme_light_tertiary = Color(0xFF417171)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFC5F0F0)
val md_theme_light_onTertiaryContainer = Color(0xFF002A2A)
val md_theme_light_error = Color(0xFFD32F2F)
val md_theme_light_errorContainer = Color(0xFFFFE2DF)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF440004)
val md_theme_light_background = Color(0xFFF9F9F2)
val md_theme_light_onBackground = Color(0xFF20241F)
val md_theme_light_surface = Color(0xFFF9F9F2)
val md_theme_light_onSurface = Color(0xFF20241F)
val md_theme_light_surfaceVariant = Color(0xFFE4E9D9)
val md_theme_light_onSurfaceVariant = Color(0xFF4B5244)
val md_theme_light_outline = Color(0xFF7D8473)
val md_theme_light_inverseOnSurface = Color(0xFFF3F3EB)
val md_theme_light_inverseSurface = Color(0xFF2B2F2B)
val md_theme_light_inversePrimary = Color(0xFF92CF8B)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF4E7B2C)
val md_theme_light_outlineVariant = Color(0xFFC9CEC0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF92CF8B)
val md_theme_dark_onPrimary = Color(0xFF143C00)
val md_theme_dark_primaryContainer = Color(0xFF2C5612)
val md_theme_dark_onPrimaryContainer = Color(0xFFBFEAB0)
val md_theme_dark_secondary = Color(0xFFB4C2A3)
val md_theme_dark_onSecondary = Color(0xFF2A381D)
val md_theme_dark_secondaryContainer = Color(0xFF414F37)
val md_theme_dark_onSecondaryContainer = Color(0xFFDFECD2)
val md_theme_dark_tertiary = Color(0xFFA4D8D8)
val md_theme_dark_onTertiary = Color(0xFF003E3E)
val md_theme_dark_tertiaryContainer = Color(0xFF254E4E)
val md_theme_dark_onTertiaryContainer = Color(0xFFC5F0F0)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFE2DF)
val md_theme_dark_background = Color(0xFF20241F)
val md_theme_dark_onBackground = Color(0xFFE5E5DD)
val md_theme_dark_surface = Color(0xFF20241F)
val md_theme_dark_onSurface = Color(0xFFE5E5DD)
val md_theme_dark_surfaceVariant = Color(0xFF4B5244)
val md_theme_dark_onSurfaceVariant = Color(0xFFC9CEC0)
val md_theme_dark_outline = Color(0xFF90978B)
val md_theme_dark_inverseOnSurface = Color(0xFF20241F)
val md_theme_dark_inverseSurface = Color(0xFFE5E5DD)
val md_theme_dark_inversePrimary = Color(0xFF4E7B2C)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF92CF8B)
val md_theme_dark_outlineVariant = Color(0xFF4B5244)
val md_theme_dark_scrim = Color(0xFF000000)

val seed = Color(0xFF2D4E1B)
